name: gha2-results

on:
  pull_request:
    branches:
      - branch-2
  push:
    branches:
      - branch-2

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk:
          - name: Oracle JDK 11
            version: '11'
          - name: Oracle JDK EA
            version: '16'
          - name: OpenJDK 11
            version: '11'
          - name: OpenJDK EA
            version: '16'
    steps:
      - name: Checkout Code
      - uses: actions/checkout@v3.5.0

      - uses: actions/setup-java@v3.12.0
        with:
            java-version: ${{ matrix.jdk.version }}
            distribution: 'zulu'

      - name: build with maven
        run:
          bash <(curl -s https://codecov.io/bash)
          mvn -q clean compile test