name: Project 3- My custom Manual Migration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [ 11 ]
        include:
          - java-version: 11
            jdk: oraclejdk11
          - java-version: 11
            jdk: openjdk11
