name: Project 3- My custom Manual Migration

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [11]
        include:
          - java-version: '11'
            distribution: 'zulu'
            jdk: 'oraclejdk11'

          - java-version: '11'
            distribution: 'zulu'
            jdk: 'openjdk11'

    steps:
      - name: Setting up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-version }}