name: Project 3- My custom Manual Migration

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [11]
        include:
          - java-version: 11
            jdk: oraclejdk11
            architecture: 'x64'
            distribution: 'adopt'

          - java-version: 11
            jdk: openjdk11
            architecture: 'x64'
            distribution: 'adopt'

    steps:
      - name: Setting up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-version }}