name: Project 3- My custom Manual Migration

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [11]
        include:
          - java-version: '11'
            jdk: 'oraclejdk11'
            distribution: 'adopt'

          - java-version: '11'
            jdk: 'openjdk11'
            distribution: 'adopt'

    steps:
      - name: Setting up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'adopt'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Installing the dependencies
        run: mvn -q install -Dgpg.skip

      - name: Build and test
        run: mvn clean package -DskipTests=false

      - name: Uploading code coverage data to the Codecov service
        run: bash <(curl -s https://codecov.io/bash)

      - name: Caching packages of Maven
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2